### ISSUE TITLE
vulkan-1.dll missing

### ISSUE THREAD

**Issue by MHumm** [tinyBigGAMES/LMEngine#2]
I'm trying to run your example project in a virtual machine and I'm sure I don't have Vulkan available there. Pressing F9 results in the failure message that vulkan-1.dll could not be found. 

Your readme.md describes that I can run it solely CPU based as well but unfortunatelly doesn't explain how I can set it up that way and the included .chm help file doesn't either.

Can you give me a clue please?
This might also help with further improving the documentation.

**Comment by JohnClaw** [comment]
> Your readme.md describes that I can run it solely CPU based as well but unfortunatelly doesn't explain how I can set it up that way and the included .chm help file doesn't either.
> 
> Can you give me a clue please?

To run LmEngine on CPU you should change this line of code: Config_Init("C:/LLM/gguf", **-1**) -> Config_Init("C:/LLM/gguf", **0**).

**Comment by jarroddavis68** [comment]
> Your readme.md describes that I can run it solely CPU based as well but unfortunatelly doesn't explain how I can set it up that way and the included .chm help file doesn't either.

Because of the split-mode feature (it is there, just not enabled yet), it will still require Vulkan to be present. For cases where you want to load a model larger than available VRAM, you can split it across GPU VRAM and CPU RAM. At the moment, it will either load fully in VRAM Config_Init("gguf_path", -1) or you can control how much on the GPU with Config_Init("gguf_path", 0) for none on the GPU (all on CPU) to up to your max GPU layers (1-33) for example. 

I will update the docs to be clearer that Vulkan must be present, just that you can use the GPU, CPU or in the case the split mode, or both.

Went with Vulcan for the widest range of GPU support with low overhead.

Note, running without a GPU will be very slow since inference is very mathematically intensive.

**Comment by MHumm** [comment]
Just to properly understand this: does this mean I cannot run this demo in my VM if that doesn't support Vulcan? Even if the VM would have enough RAM otherwise?

**Comment by jarroddavis68** [comment]
You must have a Vulkan, you can choose to run on zero GPU layers, which will be CPU only.

If you have a GPU that supports vulkan, vulkan-1.dll should already be present on your system.

**Comment by MHumm** [comment]
Thanks, I could run it successfully on the host now. Nice toy ;-)
I modified the demo to be able to ask questions I type in and when he's finished I ask if one wants to enther another question. So far so good, but it looks like the question "sums up" or is added internally to the state. Haven't seen a way yet to clear this state without unloading and reloading the model. Is there one?

Another thing: I see that the comments in lmengine.pas are in JavaDoc or something like this. If they were in XMLDOC, the IDE could pick them up and provide them as "help insight" tooltips when you hover over any such call in your code. If you like I can help with that. The IDE actually provides some support for entering such comments.

**Comment by jarroddavis68** [comment]
if you call `Message_Add`, it will accumulate the messages. If you take the response you get from the model and add it as `ROLE_ASSISTANT`, this gives you context and allows you to have a conversation. For example, if you ask, "who is bill gates?", then the response you get from the model, is added back as an assistant message, you can then ask, "does he have kids", and it will understand the context.

If you wish to clear the context, you should call `Message_ClearAll`. Note, it clears ALL messages so if you had a system message, you would need to add that back.

**Comment by jarroddavis68** [comment]
> Another thing: I see that the comments in lmengine.pas are in JavaDoc or something like this. If they were in XMLDOC, the IDE could pick them up and provide them as "help insight" tooltips when you hover over any such call in your code. If you like I can help with that. The IDE actually provides some support for entering such comments.

Yes, thanks! 👍🏿
