### ISSUE TITLE
Suggestion about CR/LF console handling

### ISSUE THREAD

**Issue by MHumm** [tinyBigGAMES/LMEngine#4]
You define constants for CR and for LF and then a concatenated one for CR/LF in LFEngine.pas. 
Wouldn't it make more sense to use the sLineBreak constant from system.pas?
That would always produce the platform specific line break.

**Comment by jarroddavis68** [comment]
LHEngine is being designed to support multiple programming languages, so I aim to minimize language-specific details and keep each language binding in sync. Initially, it will be developed for Win64. After reaching version 1.0, I will consider expanding to other platforms.

This is the goal, however, I am always open to better ways of doing things, so always feel free to offer suggestions.
